version: "3.3"
services:
  redis:
    image: redis:7.0.14-alpine
    ports:
      - '6379:6379'
    network_mode: "host"
  # status-service:
  #   image: metalheart/status-service:latest
  #   depends_on:
  #     - redis
  #   network_mode: "host"
