version: "3.3"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
  
  telegraf:
    image: telegraf:1.8
    volumes:
     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
     - 9100:9100
     - 8186:8186
  
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - telegraf
  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
  redis_exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
      - '9121:9121'
    depends_on:
      - redis
      - prometheus
  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'
  #   depends_on:
  #     - prometheus

  # status-service:
  #   image: metalheart/status-service:latest
  #   depends_on:
  #     - redis
  #   network_mode: "host"
