version: "3.3"

services:

  ############################################################
  #                    DATASOURCES                           #
  ############################################################

  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'

  nginx:
    build:
      context: ./nginx
      target: dev
    image: nginx:1.25.3-alpine3.18
    container_name: nginx-www
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:rw
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443

  ############################################################
  #                     MONITORING                           #
  ############################################################
  redis_exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
      - '9121:9121'
    depends_on:
      - redis

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      #- '--collector.systemd'
      - '--collector.processes'
    ports:
      - '9100:9100'
    depends_on:
      - prometheus

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    env_file: .env
    command:
      - --nginx.scrape-uri=https://nginx/stub_status
    ports:
      - '9113:9113'
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
  # status-service:
  #   image: metalheart/status-service:latest
  #   depends_on:
  #     - redis
  #   network_mode: "host"
