{
 "title": "Status service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(status_service_uptime_in_seconds[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "status_service_http_request_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "status_service_rss_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(sum by(instance) (irate(status_service_cpu_seconds_total[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(status_service_cpu_seconds_total[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total http requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "status_service_http_request_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}