global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: status-service
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:8880']